#CREATING TABLE 
CREATE TABLE MOBILECOMPANY1(
   ID INT     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   SECTION      CHAR(50),
   SALARY         REAL
);
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(01, 'Arunprasath', 18, 'APP DEVELOPER', 70000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(02, 'Sivakumar', 19, 'PUBLISHER', 90000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(03, 'Deepak', 18, 'WEB DEVELOPER', 70000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(04, 'Santhosh', 19, 'ASSEMBELER', 67000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(05, 'Yasar', 18, 'DEBUG ENGINEER', 70000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(06, 'Nataraj', 19, 'SOFTWARE DEVELOPER', 50000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(07, 'Keerthana', 20, 'FINANCE DEPT', 80000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(09, 'Aadhila', 18, 'EXECUTIVE DEPT', 72000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(10, 'Prem', 19, 'GAME DEVELOPER', 55000)
INSERT INTO MOBILECOMPANY1 (ID,NAME,AGE,SECTION,SALARY)VALUES(12, 'Sabari', 19, 'CO-PRODUCER', 90000)
select *from MOBILECOMPANY1;
 

#LOGICAL OPERATIONS AND,OR,NOT

SELECT * FROM MOBILECOMPANY1 WHERE SALARY BETWEEN 50000 AND 90000; 
SELECT * FROM MOBILECOMPANY1 WHERE NAME = 'Deepak' OR SECTION = 'WEB DEVELOPER';  
SELECT * FROM MOBILECOMPANY1 WHERE NOT SECTION = 'EXECUTIVE DEPT';  

# CREATING ANOTHER TABLE 
CREATE TABLE MOBILECOMPANY2(
   ID INT     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   GRADE          CHAR(20)    NOT NULL
);
select *from MOBILECOMPANY2;
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(01, 'Prasath', 18, 'A');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(02, 'Kumar', 19, 'A+');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(03, 'Vaseekaran', 18, 'O');
INSERT INTO MOBILECOMPANY2(ID,NAME,AGE,GRADE)VALUES(04, 'Manoj', 19, 'A');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(05, 'Ajmal', 18, 'B');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(06, 'Nived', 18, 'AB');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(07, 'Jaya', 19, 'O');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(09, 'Jagan', 18, 'B');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(10, 'Shamitha', 19, 'A');
INSERT INTO MOBILECOMPANY2 (ID,NAME,AGE,GRADE)VALUES(12, 'Mohan', 24, 'O');
SELECT*FROM MOBILECOMPANY2

#MIN AND MAX

SELECT MIN(SALARY) AS MINSALARY
FROM MOBILECOMPANY1;
SELECT MAX(SALARY) AS MAXSALARY
FROM MOBILECOMPANY1;

# COUNTING THE COLUMN SECTION

SELECT COUNT(SECTION)
FROM MOBILECOMPANY1;

#AVERAGE

SELECT AVG(SALARY)
FROM MOBILECOMPANY1;

#LEFT JOIN 

SELECT MOBILECOMPANY1.NAME,MOBILECOMPANY2.GRADE
FROM MOBILECOMPANY1
LEFT JOIN MOBILECOMPANY2
ON MOBILECOMPANY1.ID = MOBILECOMPANY2.ID;

# RIGHT JOIN

SELECT MOBILECOMPANY2.NAME,MOBILECOMPANY1.AGE
FROM MOBILECOMPANY2
RIGHT JOIN MOBILECOMPANY1
ON MOBILECOMPANY2.ID = MOBILECOMPANY1.ID;

# FULL JOIN

SELECT MOBILECOMPANY1.NAME,MOBILECOMPANY2.AGE,MOBILECOMPANY1.SECTION,MOBILECOMPANY2.GRADE
FROM MOBILECOMPANY1
FULL OUTER JOIN MOBILECOMPANY2 ON MOBILECOMPANY2.ID = MOBILECOMPANY1.ID
ORDER BY MOBILECOMPANY1.NAME;

#UNION

SELECT NAME FROM MOBILECOMPANY1
UNION
SELECT NAME FROM MOBILECOMPANY2
ORDER BY NAME;

#SUM

SELECT SUM(SALARY)
FROM MOBILECOMPANY1;

#ASCENDING AND DESCENDING

SELECT * FROM MOBILECOMPANY1
ORDER BY NAME ASC;
SELECT * FROM MOBILECOMPANY2
ORDER BY NAME DESC;